### PR TITLE
Fixes to characters considered zero-width

### LINKED ISSUE #26: Hangul Jamo Extended-B should be 0-width
https://github.com/unicode-rs/unicode-width/blob/master/scripts/unicode.py#L304 has special-casing for U+1160..U+11FF (decimal 4448..4607, what's with using decimal values anyway?) (the part of the Hangul Jamo block which contains medial/vowels/jungseong and final/trailing_consonants/jongseong Jamo), to treat it as 0-width.

The Hangul Jamo Extended-B block at U+D7B0..U+D7FF contains jungseong and jongseong for Old Korean, and should be treated the same as U+1160..U+11F0.

glibc's wcwidth() treats that block as 0 width since:
```

commit 6e540caa21616d5ec5511fafb22819204525138e
Author: Mike FABIAN <mfabian@redhat.com>
Date:   Tue Jun 16 08:29:40 2020 +0200

    Set width of JUNGSEONG/JONGSEONG characters from UD7B0 to UD7FB to
0 [BZ #26120]
Reviewed-by: default avatarCarlos O'Donell <carlos@redhat.com>

diff --git a/localedata/charmaps/UTF-8 b/localedata/charmaps/UTF-8
index 14c5d4fa33..8cce47cd97 100644
--- a/localedata/charmaps/UTF-8
+++ b/localedata/charmaps/UTF-8
@@ -48920,6 +48920,8 @@ WIDTH
 <UABE8>        0
 <UABED>        0
 <UAC00>...<UD7A3>      2
+<UD7B0>...<UD7C6>      0
+<UD7CB>...<UD7FB>      0
 <UF900>...<UFA6D>      2
 <UFA70>...<UFAD9>      2
 <UFB1E>        0
```

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
These characters are supposed to be completely invisible and ignored by rendering unless specially supported: https://www.unicode.org/faq/unsup_char.html#3. [Characters affected](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3ADefault_ignorable_Code_Point%3DYes%3A%5D%26%5B%3AGeneral_Category%21%3DCf%3A%5D%26%5B%3AGeneral_Category%21%3DMn%3A%5D%26%5B%3AGeneral_Category%21%3DMe%3A%5D%26%5B%3AGeneral_Category%21%3DCc%3A%5D&g=&i=)

---

Edit: Now also fixes #26

---

Edit 2: I've marked `Prepended_Concatenation_Mark`s as not zero-width. This matches the behavior of glibc

---

Edit 3: I've given U+115F HANGUL CHOSEONG FILLER back its width 2, because it's expected to be combined with other jamo to form a width-2 syllable block.

### CODE REVIEW

**Comment by Manishearth** [comment]
This implements a [specific standardized algorithm](https://www.unicode.org/reports/tr11/) as documented in the readme. This rule around Default_Ignorable doesn't seem to be documented there.

This is _not_ a general purpose terminal width library.

**Comment by Jules-Bertholet** [comment]
This library already differs from UAX 11 in several important ways:

- This crate has special handling for the soft hyphen and certain Hangul characters, which is not mentioned in UAX 11: https://github.com/unicode-rs/unicode-width/blob/89424871950f91033de79cd06318d8c06d94df84/scripts/unicode.py#L482-L489
- UAX 11 says "[UTS51] emoji presentation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value", but this crate doesn't do that

**Comment by Manishearth** [comment]
Hmm, yeah. I didn't originally write this but I would like for the code to follow the spec first and offer these things as settings

**Comment by Jules-Bertholet** [comment]
UAX 11 doesn't really give a full, exact algorithm for getting a "width value" for a string. For example, control codes aren't even mentioned, nor are line breaks etc. So I think referring to other parts of the Unicode standard as well makes perfect sense.

**Comment by Manishearth** [comment]
Hmm that's fair. Will review later.

I would ideally like someone to take a holistic view of this crate, compare with the specs, and document/add options. Haven't had time to do this myself ever since I inherited it.

**Comment by Jules-Bertholet** [comment]
> I would ideally like someone to take a holistic view of this crate, compare with the specs, and document

I've added some comments throughout the code, but here is a summary of the current rules (with this PR's changes included):

 - The soft hyphen (`U+00AD`) is single-width. This is based on the behavior of `wcstring()`/`wcsstring()` from POSIX in various implementations. There is more background on this character at https://archive.is/fCT3c; TLDR is that the Unicode spec interprets it slightly differently than ISO Latin 1 originally did. Arguably this could be configurable.
 - Hangul jamo medial vowels & final consonants are zero-width. This is to ensure that Hangul syllable blocks, which consists of initial consonant + medial vowel + optional final consonant, have total length 2. The spec suggests that archaic Korean can have syllable blocks with more than 1 initial consonant, which might lead this crate to give wrong results for those cases? May be worth investigating. And nonstandard jamo sequences (missing an initial consonant) might be rendered with a different width than this crate says, of course.
- All `Default_Ignorable_Code_Point`s are zero-width, except for U+115F HANGUL CHOSEONG FILLER. These code points are documented by Unicode as having no rendering whatsoever unless an implementation specifically supports them. U+115F is exempted, however, because it is meant for Hangul syllable blocks that are specifically missing their initial consonant on purpose, but that still have a medial vowel and/or final consonant. So, because we still want the complete block to have length 2, we give it length 2.
- All nonspacing marks (general category `Mn`, or `Me`), as well as control (`Cc`) and format (`Cf`) characters are zero-width, except for `Prepended_Concatenation_Mark`s which take up space in front of what they format.
- Otherwise, we follow UAX 11 in assigning width properties to individual characters.

What's still not handled, or could be handled differently:

- This crate could give "wrong" width for anything "malformed" (defective combining character sequences, nonstandard jamo sequences, more I don't know about maybe?)
- `UnicodeWidthChar` gives a width of `Some(0)` to U+2028 LINE SEPARATOR and U+2029 PARAGRAPH SEPARATOR, maybe these should be `None`?
- Soft hyphen situation
- Multi-choseong jamo?
- Multichar emoji sequences. #35 makes emoji presentation sequences conform to UAX 11, but emoji ZWJ sequences are not handled (as documented in the README). And there are several possible knobs if such support were to be added.
- Some non-East-Asian characters would seem to imply an extra-wide rendering, like U+2A753 TWO CONSECUTIVE EQUALS SIGNS (⩵) or the U+2E3B THREE-EM DASH (⸻). But Unicode doesn't encode this information, so this library can't realistically account for them.

**Comment by Jules-Bertholet** [comment]
https://www.unicode.org/L2/L2023/23107-terminal-suppt.pdf "Measurement" section highlights more problem cases

**Comment by Jules-Bertholet** [comment]
See also https://www.unicode.org/versions/Unicode15.1.0/ch05.pdf#G40095, "Characters Ignored for Display"

**Comment by Jules-Bertholet** [comment]
Unicode §5.21 - "Characters Ignored for Display" - "Default Ignorable Code Point" says:

> A small number of format characters (General_Category = Cf ) are also not given the Default_Ignorable_Code_Point property. This may surprise implementers, who often assume that all format characters are generally ignored in fallback display. The exact list of these exceptional format characters can be found in the Unicode Character Database. There are, however, three important sets of such format characters to note:
>
> - prepended concatenation marks
> - interlinear annotation characters
> - Egyptian hieroglyph format controls
>
> The prepended concatenation marks always have a visible display. See “Prepended Concatenation Marks” in [*Section 23.2, Layout Controls*](https://www.unicode.org/versions/Unicode15.1.0/ch23.pdf#M9.35858.HeadingBreak.132.Layout.Controls) for more discussion of the use and display of these signs.
>
> The other two notable sets of format characters that exceptionally are not ignored in fallback display consist of the interlinear annotation characters, U+FFF9 INTERLINEAR ANNOTATION ANCHOR through U+FFFB INTERLINEAR ANNOTATION TERMINATOR, and the Egyptian hieroglyph format controls, U+13430 EGYPTIAN HIEROGLYPH VERTICAL JOINER through U+1343F EGYPTIAN HIEROGLYPH END WALLED ENCLOSURE. These characters should have a visible glyph display for fallback rendering, because if they are not displayed, it is too easy to misread the resulting displayed text. See “Annotation Characters” in [*Section 23.8, Specials*](https://www.unicode.org/versions/Unicode15.1.0/ch23.pdf#M9.21335.Heading.133.Specials), as well as [*Section 11.4, Egyptian Hieroglyphs*](https://www.unicode.org/versions/Unicode15.1.0/ch11.pdf#M9.73291.Heading.1418.Egyptian.Hieroglyphs) for more discussion of the use and display of these characters.

Software that interprets the interlinear annotation anchors should probably do that processing before passing to `unicode-width`, so assuming fallback rendering makes sense in that case. Additionally, next to no implementations currently support the Egyptian hieroglyph format controls, so assuming a fallback rendering probably makes sense there as well. Therefore, I've marked both as non-zero width.

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
